[build]
  base = "withher/app"
  command = "npm install --legacy-peer-deps && node ./node_modules/expo/bin/cli export --platform web"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
